# Generated by Django 5.2.6 on 2025-09-11 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Estadodeconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'estadodeconsulta',
            },
        ),
        migrations.CreateModel(
            name='Estadodefactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'estadodefactura',
            },
        ),
        migrations.CreateModel(
            name='Historialclinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, null=True)),
                ('enfermedades', models.TextField(blank=True, null=True)),
                ('motivoconsulta', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historialclinico',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(unique=True)),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('unidaddemedida', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidadmiligramos', models.CharField(blank=True, max_length=100, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'medicamento',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correoelectronico', models.CharField(max_length=255, unique=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Piezadental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepieza', models.CharField(max_length=100)),
                ('grupo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'piezadental',
            },
        ),
        migrations.CreateModel(
            name='Recetamedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaemision', models.DateField()),
            ],
            options={
                'db_table': 'recetamedica',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costobase', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Tipodeconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreconsulta', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipodeconsulta',
            },
        ),
        migrations.CreateModel(
            name='Tipodeusuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipodeusuario',
            },
        ),
        migrations.CreateModel(
            name='Tipopago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepago', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tipopago',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaemision', models.DateField()),
                ('montototal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idestadofactura', models.ForeignKey(db_column='idestadofactura', on_delete=django.db.models.deletion.DO_NOTHING, to='api.estadodefactura')),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Documentoadjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombredocumento', models.CharField(max_length=255)),
                ('rutaarchivo', models.CharField(max_length=512)),
                ('fechacreacion', models.DateField(blank=True, null=True)),
                ('idhistorialclinico', models.ForeignKey(db_column='idhistorialclinico', on_delete=django.db.models.deletion.DO_NOTHING, to='api.historialclinico')),
            ],
            options={
                'db_table': 'documentoadjunto',
            },
        ),
        migrations.CreateModel(
            name='Itemdefactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idfactura', models.ForeignKey(db_column='idfactura', on_delete=django.db.models.deletion.DO_NOTHING, to='api.factura')),
            ],
            options={
                'db_table': 'itemdefactura',
            },
        ),
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('codusuario', models.OneToOneField(db_column='codusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.usuario')),
                ('especialidad', models.CharField(blank=True, max_length=255, null=True)),
                ('experienciaprofesional', models.TextField(blank=True, null=True)),
                ('nromatricula', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'odontologo',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('codusuario', models.OneToOneField(db_column='codusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.usuario')),
                ('carnetidentidad', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('codusuario', models.OneToOneField(db_column='codusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.usuario')),
                ('habilidadessoftware', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recepcionista',
            },
        ),
        migrations.CreateModel(
            name='Plandetratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaplan', models.DateField()),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montototal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('idestado', models.ForeignKey(db_column='idestado', on_delete=django.db.models.deletion.DO_NOTHING, to='api.estado')),
                ('cododontologo', models.ForeignKey(db_column='cododontologo', on_delete=django.db.models.deletion.DO_NOTHING, to='api.odontologo')),
                ('codpaciente', models.ForeignKey(db_column='codpaciente', on_delete=django.db.models.deletion.DO_NOTHING, to='api.paciente')),
            ],
            options={
                'db_table': 'plandetratamiento',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='idplantratamiento',
            field=models.ForeignKey(db_column='idplantratamiento', on_delete=django.db.models.deletion.DO_NOTHING, to='api.plandetratamiento'),
        ),
        migrations.CreateModel(
            name='Imtemreceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologia', models.TextField()),
                ('idmedicamento', models.ForeignKey(db_column='idmedicamento', on_delete=django.db.models.deletion.DO_NOTHING, to='api.medicamento')),
                ('idreceta', models.ForeignKey(db_column='idreceta', on_delete=django.db.models.deletion.DO_NOTHING, to='api.recetamedica')),
            ],
            options={
                'db_table': 'imtemreceta',
            },
        ),
        migrations.CreateModel(
            name='Registroodontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('fecharegistro', models.DateField()),
                ('idhistorialclinico', models.ForeignKey(db_column='idhistorialclinico', on_delete=django.db.models.deletion.DO_NOTHING, to='api.historialclinico')),
                ('idpiezadental', models.ForeignKey(db_column='idpiezadental', on_delete=django.db.models.deletion.DO_NOTHING, to='api.piezadental')),
            ],
            options={
                'db_table': 'registroodontograma',
            },
        ),
        migrations.CreateModel(
            name='Itemplandetratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costofinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idestado', models.ForeignKey(db_column='idestado', on_delete=django.db.models.deletion.DO_NOTHING, to='api.estado')),
                ('idpiezadental', models.ForeignKey(blank=True, db_column='idpiezadental', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.piezadental')),
                ('idplantratamiento', models.ForeignKey(db_column='idplantratamiento', on_delete=django.db.models.deletion.DO_NOTHING, to='api.plandetratamiento')),
                ('idservicio', models.ForeignKey(db_column='idservicio', on_delete=django.db.models.deletion.DO_NOTHING, to='api.servicio')),
            ],
            options={
                'db_table': 'itemplandetratamiento',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='idtipousuario',
            field=models.ForeignKey(db_column='idtipousuario', on_delete=django.db.models.deletion.DO_NOTHING, to='api.tipodeusuario'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montopagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechapago', models.DateField()),
                ('idfactura', models.ForeignKey(db_column='idfactura', on_delete=django.db.models.deletion.DO_NOTHING, to='api.factura')),
                ('idtipopago', models.ForeignKey(db_column='idtipopago', on_delete=django.db.models.deletion.DO_NOTHING, to='api.tipopago')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='cododontologo',
            field=models.ForeignKey(db_column='cododontologo', on_delete=django.db.models.deletion.DO_NOTHING, to='api.odontologo'),
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='codpaciente',
            field=models.ForeignKey(db_column='codpaciente', on_delete=django.db.models.deletion.DO_NOTHING, to='api.paciente'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='pacientecodigo',
            field=models.OneToOneField(db_column='pacientecodigo', on_delete=django.db.models.deletion.DO_NOTHING, to='api.paciente'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('idestadoconsulta', models.ForeignKey(db_column='idestadoconsulta', on_delete=django.db.models.deletion.DO_NOTHING, to='api.estadodeconsulta')),
                ('idhorario', models.ForeignKey(db_column='idhorario', on_delete=django.db.models.deletion.DO_NOTHING, to='api.horario')),
                ('idtipoconsulta', models.ForeignKey(db_column='idtipoconsulta', on_delete=django.db.models.deletion.DO_NOTHING, to='api.tipodeconsulta')),
                ('cododontologo', models.ForeignKey(blank=True, db_column='cododontologo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.odontologo')),
                ('codpaciente', models.ForeignKey(db_column='codpaciente', on_delete=django.db.models.deletion.DO_NOTHING, to='api.paciente')),
                ('codrecepcionista', models.ForeignKey(blank=True, db_column='codrecepcionista', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.recepcionista')),
            ],
            options={
                'db_table': 'consulta',
            },
        ),
    ]
