# Generated by Django 5.2.6 on 2025-09-09 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documentoadjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombredocumento', models.CharField(max_length=255)),
                ('rutaarchivo', models.CharField(max_length=512)),
                ('fechacreacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documentoadjunto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadodeconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'estadodeconsulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadodefactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'estadodefactura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaemision', models.DateField()),
                ('montototal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historialclinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, null=True)),
                ('enfermedades', models.TextField(blank=True, null=True)),
                ('motivoconsulta', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historialclinico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(unique=True)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imtemreceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologia', models.TextField()),
            ],
            options={
                'db_table': 'imtemreceta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('unidaddemedida', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itemdefactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'itemdefactura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itemplandetratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costofinal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'itemplandetratamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidadmiligramos', models.CharField(blank=True, max_length=100, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correoelectronico', models.CharField(max_length=255, unique=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montopagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechapago', models.DateField()),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Piezadental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepieza', models.CharField(max_length=100)),
                ('grupo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'piezadental',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plandetratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaplan', models.DateField()),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montototal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'plandetratamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recetamedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaemision', models.DateField()),
            ],
            options={
                'db_table': 'recetamedica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registroodontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('fecharegistro', models.DateField()),
            ],
            options={
                'db_table': 'registroodontograma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costobase', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodeconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreconsulta', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipodeconsulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodeusuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipodeusuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipopago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepago', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tipopago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('codusuario', models.OneToOneField(db_column='codusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.usuario')),
                ('especialidad', models.CharField(blank=True, max_length=255, null=True)),
                ('experienciaprofesional', models.TextField(blank=True, null=True)),
                ('nromatricula', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'odontologo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('codusuario', models.OneToOneField(db_column='codusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.usuario')),
                ('carnetidentidad', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('codusuario', models.OneToOneField(db_column='codusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.usuario')),
                ('habilidadessoftware', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recepcionista',
                'managed': False,
            },
        ),
    ]
