# Generated by Django 5.2.6 on 2025-09-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_notification_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recibir_notificaciones',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Vista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('ruta', models.CharField(blank=True, default='', max_length=200)),
                ('plataforma', models.CharField(choices=[('web', 'Web'), ('mobile', 'Móvil')], default='web', max_length=10)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('roles_permitidos', models.ManyToManyField(blank=True, related_name='vistas_permitidas', to='api.tipodeusuario')),
            ],
            options={
                'verbose_name': 'Vista',
                'verbose_name_plural': 'Vistas',
                'db_table': 'vista',
                'ordering': ('plataforma', 'nombre'),
            },
        ),
    ]
