# Generated by Django 5.2.6 on 2025-09-14 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuario_recibir_notificaciones_vista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('registro', 'Registro de usuario'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('crear_cita', 'Crear cita'), ('modificar_cita', 'Modificar cita'), ('eliminar_cita', 'Eliminar cita'), ('crear_paciente', 'Crear paciente'), ('modificar_paciente', 'Modificar paciente'), ('crear_usuario', 'Crear usuario'), ('modificar_usuario', 'Modificar usuario'), ('eliminar_usuario', 'Eliminar usuario'), ('acceso_dashboard', 'Acceso al dashboard'), ('otro', 'Otra acción')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('modelo_afectado', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='codusuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario')),
            ],
            options={
                'db_table': 'bitacora',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
