# Generated by Django 5.2.6 on 2025-09-15 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_system'),
        ('api', '0004_bitacora'),
    ]

    operations = [
    ]
