# Generated by Django 5.2.6 on 2025-10-01 23:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_0002_notification_system_0004_bitacora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialclinico',
            options={'ordering': ['-fecha', '-episodio']},
        ),
        migrations.RemoveConstraint(
            model_name='plantillanotificacion',
            name='unique_plantilla_tipo_canal',
        ),
        migrations.RemoveConstraint(
            model_name='preferencianotificacion',
            name='unique_preferencia_usuario',
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='pacientecodigo',
            field=models.ForeignKey(db_column='pacientecodigo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='historias', to='api.paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='plantillanotificacion',
            unique_together={('tipo_notificacion', 'canal_notificacion')},
        ),
        migrations.AlterUniqueTogether(
            name='preferencianotificacion',
            unique_together={('usuario', 'tipo_notificacion', 'canal_notificacion')},
        ),
    ]
