# Generated by Django 5.2.6 on 2025-10-12 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_stripe_fields_to_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmpresaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Si está inactivo, no puede acceder al admin')),
                ('empresa', models.ForeignKey(help_text='Empresa que este admin puede gestionar', on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='api.empresa')),
                ('user', models.OneToOneField(help_text='Usuario Django (staff) que administra la empresa', on_delete=django.db.models.deletion.CASCADE, related_name='admin_empresa_perfil', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(blank=True, help_text='Vínculo opcional con Usuario del sistema de negocio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_admin', to='api.usuario')),
            ],
            options={
                'verbose_name': 'Perfil Admin Empresa',
                'verbose_name_plural': 'Perfiles Admin Empresa',
                'db_table': 'admin_empresa_perfil',
                'unique_together': {('user', 'empresa')},
            },
        ),
    ]
