# Generated by Django 5.2.6 on 2025-10-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_admin_empresa_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estadodeconsulta',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estadodefactura',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tipopago',
            name='nombrepago',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='estado',
            unique_together={('estado', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='estadodeconsulta',
            unique_together={('estado', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='estadodefactura',
            unique_together={('estado', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('hora', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='tipopago',
            unique_together={('nombrepago', 'empresa')},
        ),
    ]
