# Generated by Django 5.2.6 on 2025-10-12 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_estado_estado_alter_estadodeconsulta_estado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipodeconsulta',
            unique_together={('nombreconsulta', 'empresa')},
        ),
    ]
