# Generated by Django 5.2.6 on 2025-10-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fix_bitacora_codusuario_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora',
            options={'verbose_name': 'Bitácora', 'verbose_name_plural': 'Bitácoras'},
        ),
        migrations.RenameField(
            model_name='bitacora',
            old_name='objeto_id',
            new_name='registro_id',
        ),
        migrations.RenameField(
            model_name='bitacora',
            old_name='modelo_afectado',
            new_name='tabla_afectada',
        ),
        migrations.RenameField(
            model_name='bitacora',
            old_name='datos_adicionales',
            new_name='valores_anteriores',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='valores_nuevos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='user_agent',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
