# Generated by Django 5.2.6 on 2025-10-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_bitacora_options_and_more'),
    ]

    operations = [
        # Las tablas 'estado' y 'estadodeconsulta' ya existen en la base de datos
        # Por lo tanto, no necesitamos crear estos modelos
    ]
