# Generated by Django 5.2.6 on 2025-10-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_documentoclinico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('subdomain', models.CharField(blank=True, help_text='Subdominio para acceso multi-tenant (ej: clinica1, clinica2)', max_length=100, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la empresa está activa en el sistema')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'api_empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='episodio',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='imtemreceta',
            table='itemreceta',
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto_contenido', models.TextField()),
                ('firma_base64', models.TextField(help_text='Firma del paciente guardada en formato Base64')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ip_creacion', models.GenericIPAddressField()),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='api.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='api.paciente')),
                ('plan_tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='api.plandetratamiento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
                'db_table': 'api_consentimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='bitacora',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cosultas', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='documentoadjunto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentosAdjuntos', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='estado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='estadodeconsulta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_consulta', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='estadodefactura',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_factura', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='horario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='imtemreceta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsReceta', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='itemdefactura',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsFacturas', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='itemplandetratamiento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsPlanesTratamientos', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontologos', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='pago',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='piezadental',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piezas_dentales', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planesTratamientos', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepcionistas', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='registroodontograma',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrosOdontogramas', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='tipodeconsulta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_consulta', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='tipodeusuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_usuario', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_pago', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='api.empresa'),
        ),
        migrations.AddConstraint(
            model_name='historialclinico',
            constraint=models.UniqueConstraint(fields=('pacientecodigo', 'episodio'), name='uniq_historial_paciente_episodio'),
        ),
    ]
