# Generated by Django 5.2.6 on 2025-10-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_set_fecha_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('texto_contenido', models.TextField()),
                ('firma_base64', models.TextField(help_text='Firma del paciente guardada en formato Base64')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ip_creacion', models.GenericIPAddressField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='api.paciente')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='api.consulta')),
                ('plan_tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='api.plandetratamiento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='api.empresa')),
            ],
            options={
                'db_table': 'api_consentimiento',
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]