# Generated by Django 5.2.6 on 2025-10-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20251012_1415'),
        ('api', '0013_consentimiento_updates'),
    ]

    operations = [
    ]