# Generated by Django 5.2.6 on 2025-10-13 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20251012_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimiento',
            name='fecha_hora_sello',
            field=models.DateTimeField(help_text='Fecha y hora del sellado digital', null=True),
        ),
        migrations.AddField(
            model_name='consentimiento',
            name='fecha_validacion',
            field=models.DateTimeField(help_text='Fecha y hora de validación', null=True),
        ),
        migrations.AddField(
            model_name='consentimiento',
            name='hash_documento',
            field=models.CharField(help_text='Hash SHA-256 del documento firmado', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='consentimiento',
            name='pdf_firmado',
            field=models.BinaryField(help_text='PDF del consentimiento con firma digital', null=True),
        ),
        migrations.AddField(
            model_name='consentimiento',
            name='validado_por',
            field=models.ForeignKey(help_text='Usuario que validó el consentimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_validados', to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='consentimiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
